<?php

class Foyer extends BaseController
{
    protected $view = "foyerView";
    protected $title = "Seb's Chats";

    public function render()
    {
        parent::render(); // TODO: Change the autogenerated stub

        $sRoomName = htmlspecialchars($this->getRequestParameter("room_name"));
        $sUser = htmlspecialchars($this->getRequestParameter("user"));
        $sAction = $this->getRequestParameter("action");
        $_SESSION["user"] = $sUser;

        if ($sAction === "join") {
            $this->redirect($this->getUrl("index.php?controller=Chat&chat=".urlencode($sRoomName)));
            exit();
        } elseif ($sAction === "create") {
            $oChatRoom = new ChatRoom();
            $oChatRoom->setRoom_name($sRoomName);
            $oChatRoom->save();
            $this->redirect($this->getUrl("index.php?controller=Chat&chat=".urlencode($sRoomName)));
            exit();
        }
    }

}